grpc_client:
  address: compute.api.cloud.yandex.net

revival_config:
  check_health_period: 30s

  instances: # ids of instances to revive
    - instance_id: epd0husgmpui1uhu9sv9
      check_health_period: 30s
